{% set name = "python_http_client" %}
{% set version = "3.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2aef67b4f49147e623f35f32b82756e30844a8f1b55a8c7c219de694f4818214

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - python_http_client

about:
  home: https://github.com/sendgrid/sendgrid-python/
  license: MIT
  license_family: MIT
  # https://github.com/sendgrid/python-http-client/pull/87
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE.txt
  summary: SendGrid's Python HTTP Client for calling APIs
  description: Quickly and easily access any RESTful or RESTful-like API
  doc_url: https://github.com/sendgrid/python-http-client
  dev_url: https://github.com/sendgrid/python-http-client

extra:
  recipe-maintainers:
    - RohitK89
    - mariusvniekerk
