{% set name = "python_http_client" %}
{% set version = "3.2.1" %}
{% set file_ext = "tar.gz" %}
{% set hash_value = "c2776054245db376ea26c859b80e9280b1a470b96ed998d60d35951f89bbbe79" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: '{{ hash_value }}'

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - python_http_client

about:
  home: https://github.com/sendgrid/sendgrid-python/
  license: MIT
  license_family: MIT
  # https://github.com/sendgrid/python-http-client/pull/87
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE.txt'
  summary: "SendGrid's Python HTTP Client for calling APIs"
  description: "Quickly and easily access any RESTful or RESTful-like API"
  doc_url: 'https://github.com/sendgrid/python-http-client'
  dev_url: 'https://github.com/sendgrid/python-http-client'

extra:
  recipe-maintainers:
    - RohitK89
    - mariusvniekerk
